__title__ = "archive_diff"
__description__ = "Tool to compare archive files without extracting them."
__url__ = "https://github.com/JBamberger/archive-diff"
__version__ = "0.1.0"
__author__ = "Jannik Bamberger"
__author_email__ = "mail@jbamberger.de"
__license__ = "MIT"
__copyright__ = "Copyright 2022 Jannik Bamberger"